### ISSUE TITLE
plexdrive stops every night around same time

### ISSUE THREAD

**Issue by tieubao81** [plexdrive/plexdrive#373]
For the last week or so, every night around 0300 - 0500 my plexdrive stops due to some fuse error.  Was just wondering if any of you are experiencing the same thing? I'm running plexdrive on an old mac mini running macos 10.11 (El Capitan)

The command I use for plexdrive is this:
/Users/plex/plexdrive5.1 mount -c /Users/plex/.plexdrive --chunk-check-threads=16 --chunk-load-threads=16 --chunk-load-ahead=16 --max-chunks=512 -o allow_other -v 4 --refresh-interval=1m /Users/plex/gdrive

Here's the error log:
[USERS/plex/PLEXDRIVE5.1] [2020-07-14 04:21] DEBUG  : Last change id found, continuing getting changes (1449910)
[USERS/plex/PLEXDRIVE5.1] [2020-07-14 04:21] DEBUG  : Storing page token 1449910 in cache
[USERS/plex/PLEXDRIVE5.1] [2020-07-14 04:22] DEBUG  : Checking for changes
[USERS/plex/PLEXDRIVE5.1] [2020-07-14 04:22] DEBUG  : Getting start page token from cache
[USERS/plex/PLEXDRIVE5.1] [2020-07-14 04:22] TRACE  : Got start page token 1449910
[USERS/plex/PLEXDRIVE5.1] [2020-07-14 04:22] DEBUG  : Last change id found, continuing getting changes (1449910)
[USERS/plex/PLEXDRIVE5.1] [2020-07-14 04:22] DEBUG  : Storing page token 1449910 in cache
[USERS/plex/PLEXDRIVE5.1] [2020-07-14 04:23] DEBUG  : Deleted chunk 1wB8e8gcbc3r-vKbj3BSu2PSnnb1BCb2k:859832320
[USERS/plex/PLEXDRIVE5.1] [2020-07-14 04:23] TRACE  : FUSE -> [ID=0x89] Read 8425472
[USERS/plex/PLEXDRIVE5.1] [2020-07-14 04:23] TRACE  : FUSE kernel write error: error="socket is not connected" stack=
goroutine 4133827 [running]:
bazil.org/fuse.stack(...)
        /go/src/bazil.org/fuse/debug.go:9
bazil.org/fuse.(*Conn).respond(0xc0000b1560, 0xc01b720000, 0x809010, 0x809010)
        /go/src/bazil.org/fuse/fuse.go:1144 +0xdc
bazil.org/fuse.(*Header).respond(0xc00025cc40, 0xc01b720000, 0x809010, 0x809010)
        /go/src/bazil.org/fuse/fuse.go:313 +0x61
bazil.org/fuse.(*ReadRequest).Respond(0xc00025cc40, 0xc007d34a80)
        /go/src/bazil.org/fuse/fuse.go:1794 +0xcd
bazil.org/fuse/fs.(*Server).handleRequest(0xc0003ea000, 0x16c5300, 0xc2d1b3ae40, 0x16ba120, 0xc270bde8a0, 0xc0f178ccc0, 0x16c3540, 0xc00025cc40, 0xc00f617eb0, 0xa8ad6291c4a4c040, ...)
        /go/src/bazil.org/fuse/fs/serve.go:1247 +0x7a6
bazil.org/fuse/fs.(*Server).serve(0xc0003ea000, 0x16c3540, 0xc00025cc40)
        /go/src/bazil.org/fuse/fs/serve.go:871 +0x406
bazil.org/fuse/fs.(*Server).Serve.func1(0xc0003ea000, 0x16c3540, 0xc00025cc40)
        /go/src/bazil.org/fuse/fs/serve.go:425 +0x6f
created by bazil.org/fuse/fs.(*Server).Serve
        /go/src/bazil.org/fuse/fs/serve.go:423 +0x35a

[USERS/plex/PLEXDRIVE5.1] [2020-07-14 04:23] INFO   : Unmounting path /Users/plex/gdrive
[USERS/plex/PLEXDRIVE5.1] [2020-07-14 04:23] DEBUG  : Closing cache file

**Comment by zmike808** [comment]
honestly I'm not sure why your chunk lookahead is so high. you Would be better off using a look ahead of 4 to 8 and Increasing the size of each chuck to 5 to 10 MB each.￼￼
With a maximum chunk count of 512 And 16 look ahead for each "file". You're probably Having some weird race condition. At least that's my best guess. 

I've had plex drive run stable For a month or more. Actually, I've never had a crash. I've always had to reboot my server for other reasons.

**Comment by felixbuenemann** [comment]
How much memory does the Mac Mini have?

With the default chunk size of 10 MiB and 512 chunks, I would expect around 6 to 8 GiB of memory usage for Plexdrive when the cache is full. 

If it always happens around the same time, I would also make sure no excessive disk access is caused by Plex maintenance tasks. Make sure you disable video thumbnails, deep media analysis and intro detection.

I would also suggest to ensure you have the latest compatible version of FUSE for macIS (osxfuse) installed. 

Btw. a preload (chunk-load-ahead) setting of 16 is extreme and will lead to very slow seeking. Try a setting of 2 or 3 chunks, it is enough for me even with 4K 120 Mbps streams.

Similarly having 16 load ahead threads is probably overkill, since a single connection to google drive can usually hit 100 MBps, so you would need about 2 GBps WAN connection to saturate those load threads.

**Comment by tieubao81** [comment]
The mac mini has 16gb of ram.  I did what you recommended, updated osxfuse... it was running good for 2 days, but then this happened again. This time I ran with this command: /Users/plex/plexdrive5.1 mount -c /Users/plex/.plexdrive -v 4 -o allow_other /Users/plex/gdrive

p[] <nil> map[]   <nil> <nil> <nil> 0xc000180020}
[USERS/plex/PLEXDRIVE5.1] [2020-07-16 21:51] DEBUG  : Deleted chunk 1153npScy73AYuC7IDy384z0o8I0a6dXb:964689920
[USERS/plex/PLEXDRIVE5.1] [2020-07-16 21:51] TRACE  : FUSE -> [ID=0xbb] Read 32768
[USERS/plex/PLEXDRIVE5.1] [2020-07-16 21:51] TRACE  : FUSE kernel write error: error="socket is not connected" stack=
goroutine 11608510 [running]:
bazil.org/fuse.stack(...)
        /go/src/bazil.org/fuse/debug.go:9
bazil.org/fuse.(*Conn).respond(0xc0002de420, 0xc00051c000, 0x8010, 0x8010)
        /go/src/bazil.org/fuse/fuse.go:1144 +0xdc
bazil.org/fuse.(*Header).respond(0xc00022e000, 0xc00051c000, 0x8010, 0x8010)
        /go/src/bazil.org/fuse/fuse.go:313 +0x61
bazil.org/fuse.(*ReadRequest).Respond(0xc00022e000, 0xc000672020)
        /go/src/bazil.org/fuse/fuse.go:1794 +0xcd
bazil.org/fuse/fs.(*Server).handleRequest(0xc0000fe000, 0x16c5300, 0xc006066000, 0x16ba120, 0xc00c139830, 0xc00f499680, 0x16c3540, 0xc00022e000, 0xc000599eb0, 0xc0001821e0, ...)
        /go/src/bazil.org/fuse/fs/serve.go:1247 +0x7a6
bazil.org/fuse/fs.(*Server).serve(0xc0000fe000, 0x16c3540, 0xc00022e000)
        /go/src/bazil.org/fuse/fs/serve.go:871 +0x406
bazil.org/fuse/fs.(*Server).Serve.func1(0xc0000fe000, 0x16c3540, 0xc00022e000)
        /go/src/bazil.org/fuse/fs/serve.go:425 +0x6f
created by bazil.org/fuse/fs.(*Server).Serve
        /go/src/bazil.org/fuse/fs/serve.go:423 +0x35a

[USERS/plex/PLEXDRIVE5.1] [2020-07-16 21:52] DEBUG  : Checking for changes
[USERS/plex/PLEXDRIVE5.1] [2020-07-16 21:52] DEBUG  : Getting start page token from cache
[USERS/plex/PLEXDRIVE5.1] [2020-07-16 21:52] TRACE  : Got start page token 1451970
[USERS/plex/PLEXDRIVE5.1] [2020-07-16 21:52] DEBUG  : Last change id found, continuing getting changes (1451970)
[USERS/plex/PLEXDRIVE5.1] [2020-07-16 21:52] TRACE  : Change &{file <nil>  0xc0001e2300 1BH47CA41eo94fDzR_Tutp5zU2GKNFDpB  false <nil>    [] []}
[USERS/plex/PLEXDRIVE5.1] [2020-07-16 21:52] TRACE  : Converting Google Drive file: &{map[] 0xc0001442d0 <nil> false    false map[]    false false   1BH47CA41eo94fDzR_Tutp5zU2GKNFDpB <nil> false  <nil>  video/mp4 false  2018-10-27T16:01:46.000Z mts.18.10.27.jessa.rhodes.my.sexy.stepmom.mp4  false [] [1GcZO_onT3jSI52Bllu32Ej0hboN0HrNn] [] [] map[] 0 false  <nil> 2575173662 [] false   0 false  <nil> 0 <nil> false  false   false {0 map[]} [] []}
[USERS/plex/PLEXDRIVE5.1] [2020-07-16 21:52] INFO   : Processed 1 items / deleted 0 items / updated 1 items
[USERS/plex/PLEXDRIVE5.1] [2020-07-16 21:52] DEBUG  : Storing page token 1451971 in cache
[USERS/plex/PLEXDRIVE5.1] [2020-07-16 21:53] DEBUG  : Checking for changes
[USERS/plex/PLEXDRIVE5.1] [2020-07-16 21:53] DEBUG  : Getting start page token from cache
[USERS/plex/PLEXDRIVE5.1] [2020-07-16 21:53] TRACE  : Got start page token 1451971
[USERS/plex/PLEXDRIVE5.1] [2020-07-16 21:53] DEBUG  : Last change id found, continuing getting changes (1451971)
[USERS/plex/PLEXDRIVE5.1] [2020-07-16 21:53] DEBUG  : Storing page token 1451971 in cache
[USERS/plex/PLEXDRIVE5.1] [2020-07-16 21:53] DEBUG  : Deleted chunk 1153npScy73AYuC7IDy384z0o8I0a6dXb:985661440
[USERS/plex/PLEXDRIVE5.1] [2020-07-16 21:53] DEBUG  : Deleted chunk 1153npScy73AYuC7IDy384z0o8I0a6dXb:996147200
[USERS/plex/PLEXDRIVE5.1] [2020-07-16 21:53] TRACE  : FUSE -> [ID=0xf] Read 4980736
[USERS/plex/PLEXDRIVE5.1] [2020-07-16 21:53] TRACE  : FUSE kernel write error: error="socket is not connected" stack=
goroutine 11608064 [running]:
bazil.org/fuse.stack(...)
        /go/src/bazil.org/fuse/debug.go:9
bazil.org/fuse.(*Conn).respond(0xc0002de420, 0xc016498000, 0x4c0010, 0x4c0010)
        /go/src/bazil.org/fuse/fuse.go:1144 +0xdc
bazil.org/fuse.(*Header).respond(0xc00022e1c0, 0xc016498000, 0x4c0010, 0x4c0010)
        /go/src/bazil.org/fuse/fuse.go:313 +0x61
bazil.org/fuse.(*ReadRequest).Respond(0xc00022e1c0, 0xc0002945c0)
        /go/src/bazil.org/fuse/fuse.go:1794 +0xcd
bazil.org/fuse/fs.(*Server).handleRequest(0xc0000fe000, 0x16c5300, 0xc006066c80, 0x16ba120, 0xc00c834600, 0xc005dc0840, 0x16c3540, 0xc00022e1c0, 0xc00059beb0, 0x13, ...)
        /go/src/bazil.org/fuse/fs/serve.go:1247 +0x7a6
bazil.org/fuse/fs.(*Server).serve(0xc0000fe000, 0x16c3540, 0xc00022e1c0)
        /go/src/bazil.org/fuse/fs/serve.go:871 +0x406
bazil.org/fuse/fs.(*Server).Serve.func1(0xc0000fe000, 0x16c3540, 0xc00022e1c0)
        /go/src/bazil.org/fuse/fs/serve.go:425 +0x6f
created by bazil.org/fuse/fs.(*Server).Serve
        /go/src/bazil.org/fuse/fs/serve.go:423 +0x35a

[USERS/plex/PLEXDRIVE5.1] [2020-07-16 21:53] INFO   : Unmounting path /Users/plex/gdrive
[USERS/plex/PLEXDRIVE5.1] [2020-07-16 21:53] DEBUG  : Closing cache file
