### ISSUE TITLE
Plexdrive and Jellyfin cannot find new files

### ISSUE THREAD

**Issue by herodev1337** [plexdrive/plexdrive#398]
Hey,
I'm using plexdrive in combination with jellyfin. It works perfectly besides that it cant find new files i added while plexdrive is mounted.

My mount command: _./plexdrive mount -c /root/.plexdrive -o allow_other -v 4 --drive-id=XXX -v 4 /media_

My workaround is:
1. kill plexdrive and start an rclone mount
2. Start a jellyfin Libary scan
3. When complete, end rclone mount, delete cache.bolt and then restart plexdrive

I'm using the newest plexdrive and the newest jellyfin (10.7.5)

Thanks for your help

**Comment by herodev1337** [comment]
Jellyfin logs says:

[ERR] [103] MediaBrowser.Controller.Entities.BaseItem: Error retrieving children folder
System.IO.IOException: **Input/output error**
   at System.IO.Enumeration.FileSystemEnumerator`1.FindNextEntry(Byte* entryBufferPtr, Int32 bufferLength)
   at System.IO.Enumeration.FileSystemEnumerator`1.MoveNext()
   at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
   at System.Collections.Generic.LargeArrayBuilder`1.AddRange(IEnumerable`1 items)
   at System.Collections.Generic.SparseArrayBuilder`1.ReserveOrAdd(IEnumerable`1 items)
   at System.Linq.Enumerable.Concat2Iterator`1.ToArray()
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at MediaBrowser.Controller.Entities.Folder.GetNonCachedChildren(IDirectoryService directoryService)
   at MediaBrowser.Controller.Entities.Folder.ValidateChildrenInternal2(IProgress`1 progress, CancellationToken cancellationToken, Boolean recursive, Boolean refreshChildMetadata, MetadataRefreshOptions refreshOptions, IDirectoryService directoryService)
